// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup top module instance
    , TOP{this, namep}
{
    // Check resources
    Verilated::stackCheck(2368);
    // Setup sub module instances
    TOP__holy_test_harness__DOT__axi.ctor(this, "holy_test_harness.axi");
    TOP__holy_test_harness__DOT__core__DOT__m_axi_data.ctor(this, "holy_test_harness.core.m_axi_data");
    TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.ctor(this, "holy_test_harness.core.m_axi_instr");
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    TOP.__PVT__holy_test_harness__DOT__axi = &TOP__holy_test_harness__DOT__axi;
    TOP.__PVT__holy_test_harness__DOT__core__DOT__m_axi_data = &TOP__holy_test_harness__DOT__core__DOT__m_axi_data;
    TOP.__PVT__holy_test_harness__DOT__core__DOT__m_axi_instr = &TOP__holy_test_harness__DOT__core__DOT__m_axi_instr;
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    TOP__holy_test_harness__DOT__axi.__Vconfigure(true);
    TOP__holy_test_harness__DOT__core__DOT__m_axi_data.__Vconfigure(false);
    TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.__Vconfigure(false);
    // Setup scopes
    __Vscopep_holy_test_harness = new VerilatedScope{this, "holy_test_harness", "holy_test_harness", "holy_test_harness", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__axi = new VerilatedScope{this, "holy_test_harness.axi", "axi", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core = new VerilatedScope{this, "holy_test_harness.core", "core", "cpu", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__alu_inst = new VerilatedScope{this, "holy_test_harness.core.alu_inst", "alu_inst", "alu", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__arbiter = new VerilatedScope{this, "holy_test_harness.core.arbiter", "arbiter", "external_req_arbiter", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__control_unit = new VerilatedScope{this, "holy_test_harness.core.control_unit", "control_unit", "control", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__csr = new VerilatedScope{this, "holy_test_harness.core.csr", "csr", "csr", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__data_cache = new VerilatedScope{this, "holy_test_harness.core.data_cache", "data_cache", "holy_cache", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__instr_cache = new VerilatedScope{this, "holy_test_harness.core.instr_cache", "instr_cache", "holy_cache", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__m_axi_data = new VerilatedScope{this, "holy_test_harness.core.m_axi_data", "m_axi_data", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__m_axi_instr = new VerilatedScope{this, "holy_test_harness.core.m_axi_instr", "m_axi_instr", "axi_if", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__regfile = new VerilatedScope{this, "holy_test_harness.core.regfile", "regfile", "regfile", -9, VerilatedScope::SCOPE_MODULE};
    __Vscopep_holy_test_harness__core__regfile__unnamedblk1 = new VerilatedScope{this, "holy_test_harness.core.regfile.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER};
    __Vscopep_holy_test_harness__core__sign_extender = new VerilatedScope{this, "holy_test_harness.core.sign_extender", "sign_extender", "signext", -9, VerilatedScope::SCOPE_MODULE};
    // Set up scope hierarchy
    __Vhier.add(0, __Vscopep_holy_test_harness);
    __Vhier.add(__Vscopep_holy_test_harness, __Vscopep_holy_test_harness__axi);
    __Vhier.add(__Vscopep_holy_test_harness, __Vscopep_holy_test_harness__core);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__alu_inst);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__arbiter);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__control_unit);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__csr);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__data_cache);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__instr_cache);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__m_axi_data);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__m_axi_instr);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__regfile);
    __Vhier.add(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__sign_extender);
    __Vhier.add(__Vscopep_holy_test_harness__core__regfile, __Vscopep_holy_test_harness__core__regfile__unnamedblk1);
    // Setup export functions - final: 0
    // Setup export functions - final: 1
    // Setup public variables
    __Vscopep_holy_test_harness->varInsert("aclk", &(TOP.holy_test_harness__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("clk", &(TOP.holy_test_harness__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_aclk", &(TOP.holy_test_harness__DOT__m_axi_mem_aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_araddr", &(TOP.holy_test_harness__DOT__m_axi_mem_araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arburst", &(TOP.holy_test_harness__DOT__m_axi_mem_arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_aresetn", &(TOP.holy_test_harness__DOT__m_axi_mem_aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arid", &(TOP.holy_test_harness__DOT__m_axi_mem_arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arlen", &(TOP.holy_test_harness__DOT__m_axi_mem_arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arready", &(TOP.holy_test_harness__DOT__m_axi_mem_arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arsize", &(TOP.holy_test_harness__DOT__m_axi_mem_arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_arvalid", &(TOP.holy_test_harness__DOT__m_axi_mem_arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awaddr", &(TOP.holy_test_harness__DOT__m_axi_mem_awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awburst", &(TOP.holy_test_harness__DOT__m_axi_mem_awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awid", &(TOP.holy_test_harness__DOT__m_axi_mem_awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awlen", &(TOP.holy_test_harness__DOT__m_axi_mem_awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awready", &(TOP.holy_test_harness__DOT__m_axi_mem_awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awsize", &(TOP.holy_test_harness__DOT__m_axi_mem_awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_awvalid", &(TOP.holy_test_harness__DOT__m_axi_mem_awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_bid", &(TOP.holy_test_harness__DOT__m_axi_mem_bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_bready", &(TOP.holy_test_harness__DOT__m_axi_mem_bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_bresp", &(TOP.holy_test_harness__DOT__m_axi_mem_bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_bvalid", &(TOP.holy_test_harness__DOT__m_axi_mem_bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rdata", &(TOP.holy_test_harness__DOT__m_axi_mem_rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rid", &(TOP.holy_test_harness__DOT__m_axi_mem_rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rlast", &(TOP.holy_test_harness__DOT__m_axi_mem_rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rready", &(TOP.holy_test_harness__DOT__m_axi_mem_rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rresp", &(TOP.holy_test_harness__DOT__m_axi_mem_rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_rvalid", &(TOP.holy_test_harness__DOT__m_axi_mem_rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_wdata", &(TOP.holy_test_harness__DOT__m_axi_mem_wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_wlast", &(TOP.holy_test_harness__DOT__m_axi_mem_wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_wready", &(TOP.holy_test_harness__DOT__m_axi_mem_wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_wstrb", &(TOP.holy_test_harness__DOT__m_axi_mem_wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness->varInsert("m_axi_mem_wvalid", &(TOP.holy_test_harness__DOT__m_axi_mem_wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness->varInsert("rst_n", &(TOP.holy_test_harness__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__axi.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__axi.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__axi.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("aclk", &(TOP__holy_test_harness__DOT__axi.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("araddr", &(TOP__holy_test_harness__DOT__axi.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("arburst", &(TOP__holy_test_harness__DOT__axi.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("aresetn", &(TOP__holy_test_harness__DOT__axi.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("arid", &(TOP__holy_test_harness__DOT__axi.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("arlen", &(TOP__holy_test_harness__DOT__axi.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__axi->varInsert("arlock", &(TOP__holy_test_harness__DOT__axi.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("arqos", &(TOP__holy_test_harness__DOT__axi.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("arready", &(TOP__holy_test_harness__DOT__axi.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("arsize", &(TOP__holy_test_harness__DOT__axi.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__axi->varInsert("arvalid", &(TOP__holy_test_harness__DOT__axi.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("awaddr", &(TOP__holy_test_harness__DOT__axi.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("awburst", &(TOP__holy_test_harness__DOT__axi.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("awid", &(TOP__holy_test_harness__DOT__axi.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("awlen", &(TOP__holy_test_harness__DOT__axi.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__axi->varInsert("awlock", &(TOP__holy_test_harness__DOT__axi.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("awqos", &(TOP__holy_test_harness__DOT__axi.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("awready", &(TOP__holy_test_harness__DOT__axi.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("awsize", &(TOP__holy_test_harness__DOT__axi.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__axi->varInsert("awvalid", &(TOP__holy_test_harness__DOT__axi.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("bid", &(TOP__holy_test_harness__DOT__axi.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("bready", &(TOP__holy_test_harness__DOT__axi.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("bresp", &(TOP__holy_test_harness__DOT__axi.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("bvalid", &(TOP__holy_test_harness__DOT__axi.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("rdata", &(TOP__holy_test_harness__DOT__axi.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("rid", &(TOP__holy_test_harness__DOT__axi.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("rlast", &(TOP__holy_test_harness__DOT__axi.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("rready", &(TOP__holy_test_harness__DOT__axi.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("rresp", &(TOP__holy_test_harness__DOT__axi.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__axi->varInsert("rvalid", &(TOP__holy_test_harness__DOT__axi.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("wdata", &(TOP__holy_test_harness__DOT__axi.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__axi->varInsert("wlast", &(TOP__holy_test_harness__DOT__axi.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("wready", &(TOP__holy_test_harness__DOT__axi.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__axi->varInsert("wstrb", &(TOP__holy_test_harness__DOT__axi.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__axi->varInsert("wvalid", &(TOP__holy_test_harness__DOT__axi.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("alu_control", &(TOP.holy_test_harness__DOT__core__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core->varInsert("alu_last_bit", &(TOP.holy_test_harness__DOT__core__DOT__alu_last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("alu_result", &(TOP.holy_test_harness__DOT__core__DOT__alu_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("alu_source", &(TOP.holy_test_harness__DOT__core__DOT__alu_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("alu_src1", &(TOP.holy_test_harness__DOT__core__DOT__alu_src1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("alu_src2", &(TOP.holy_test_harness__DOT__core__DOT__alu_src2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("alu_zero", &(TOP.holy_test_harness__DOT__core__DOT__alu_zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("branch", &(TOP.holy_test_harness__DOT__core__DOT__branch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("clk", &(TOP.holy_test_harness__DOT__core__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("csr_read_data", &(TOP.holy_test_harness__DOT__core__DOT__csr_read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("csr_write_enable", &(TOP.holy_test_harness__DOT__core__DOT__csr_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("d_cache_stall", &(TOP.holy_test_harness__DOT__core__DOT__d_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("d_cache_state", &(TOP.holy_test_harness__DOT__core__DOT__d_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core->varInsert("dest_reg", &(TOP.holy_test_harness__DOT__core__DOT__dest_reg), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core->varInsert("f3", &(TOP.holy_test_harness__DOT__core__DOT__f3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core->varInsert("f7", &(TOP.holy_test_harness__DOT__core__DOT__f7), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core->varInsert("flush_flag", &(TOP.holy_test_harness__DOT__core__DOT__flush_flag), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("global_stall", &(TOP.holy_test_harness__DOT__core__DOT__global_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("i_cache_stall", &(TOP.holy_test_harness__DOT__core__DOT__i_cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("i_cache_state", &(TOP.holy_test_harness__DOT__core__DOT__i_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core->varInsert("imm_source", &(TOP.holy_test_harness__DOT__core__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core->varInsert("immediate", &(TOP.holy_test_harness__DOT__core__DOT__immediate), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("instruction", &(TOP.holy_test_harness__DOT__core__DOT__instruction), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("jump", &(TOP.holy_test_harness__DOT__core__DOT__jump), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("mem_read", &(TOP.holy_test_harness__DOT__core__DOT__mem_read), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("mem_read_enable", &(TOP.holy_test_harness__DOT__core__DOT__mem_read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("mem_write", &(TOP.holy_test_harness__DOT__core__DOT__mem_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("op", &(TOP.holy_test_harness__DOT__core__DOT__op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core->varInsert("pc", &(TOP.holy_test_harness__DOT__core__DOT__pc), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("pc_next", &(TOP.holy_test_harness__DOT__core__DOT__pc_next), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("pc_plus_four", &(TOP.holy_test_harness__DOT__core__DOT__pc_plus_four), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("pc_source", &(TOP.holy_test_harness__DOT__core__DOT__pc_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("pc_target", &(TOP.holy_test_harness__DOT__core__DOT__pc_target), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("raw_imm", &(TOP.holy_test_harness__DOT__core__DOT__raw_imm), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,24,0);
    __Vscopep_holy_test_harness__core->varInsert("read_reg1", &(TOP.holy_test_harness__DOT__core__DOT__read_reg1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("read_reg2", &(TOP.holy_test_harness__DOT__core__DOT__read_reg2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("reg_write", &(TOP.holy_test_harness__DOT__core__DOT__reg_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("rst_n", &(TOP.holy_test_harness__DOT__core__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core->varInsert("source_reg1", &(TOP.holy_test_harness__DOT__core__DOT__source_reg1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core->varInsert("source_reg2", &(TOP.holy_test_harness__DOT__core__DOT__source_reg2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core->varInsert("write_back_data", &(TOP.holy_test_harness__DOT__core__DOT__write_back_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core->varInsert("write_back_source", &(TOP.holy_test_harness__DOT__core__DOT__write_back_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("alu_control", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("alu_last_bit", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__alu_last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("alu_result", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__alu_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("s1", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__s1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("s2", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__s2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__alu_inst->varInsert("zero", &(TOP.holy_test_harness__DOT__core__DOT__alu_inst__DOT__zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__arbiter->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.holy_test_harness__DOT__core__DOT__arbiter__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__arbiter->varInsert("d_cache_state", &(TOP.holy_test_harness__DOT__core__DOT__arbiter__DOT__d_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__arbiter->varInsert("i_cache_state", &(TOP.holy_test_harness__DOT__core__DOT__arbiter__DOT__i_cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("alu_control", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__alu_control), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("alu_last_bit", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__alu_last_bit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("alu_op", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__alu_op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("alu_source", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__alu_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("alu_zero", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__alu_zero), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("branch", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__branch), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("csr_write_enable", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__csr_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("func3", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__func3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("func7", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__func7), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("imm_source", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("jump", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__jump), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("mem_read", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__mem_read), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("mem_write", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__mem_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("op", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__op), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("pc_source", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__pc_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("reg_write", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__reg_write), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__control_unit->varInsert("write_back_source", &(TOP.holy_test_harness__DOT__core__DOT__control_unit__DOT__write_back_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("address", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__address), false, VLVT_UINT16, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,11,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("clk", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__csr->varInsert("f3", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__f3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("flush_cache", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__flush_cache), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("flush_flag", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__flush_flag), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__csr->varInsert("nand_result", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__nand_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("next_flush_cache", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__next_flush_cache), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("or_result", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__or_result), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("read_data", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("rst_n", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__csr->varInsert("write_back_to_csr", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__write_back_to_csr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("write_data", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__csr->varInsert("write_enable", &(TOP.holy_test_harness__DOT__core__DOT__csr__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("aclk", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("actual_write_enable", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__actual_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("address", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__address), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("ar_hs", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__ar_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("aw_hs", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__aw_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("b_hs", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__b_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("byte_enable", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("byte_enable_mask", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__byte_enable_mask), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_block_tag", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_data", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_data), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 2 ,127,0 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_dirty", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_stall", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_state", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("cache_valid", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("clk", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("csr_flush_status", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__csr_flush_status), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("flush_flag", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__flush_flag), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("hit", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("r_hs", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__r_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("read_data", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("read_enable", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("req_block_tag", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__req_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("req_index", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__req_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,2);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("rst_n", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("set_ptr", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("state", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("w_hs", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__w_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("write_data", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__data_cache->varInsert("write_enable", &(TOP.holy_test_harness__DOT__core__DOT__data_cache__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("CACHE_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__CACHE_SIZE))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("aclk", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("actual_write_enable", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__actual_write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("address", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__address), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("ar_hs", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__ar_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("aw_hs", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__aw_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("b_hs", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__b_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("byte_enable", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("byte_enable_mask", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__byte_enable_mask), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_block_tag", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_data", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_data), false, VLVT_WDATA, VLVD_NODIR|VLVF_PUB_RW, 0, 2 ,127,0 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_dirty", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_dirty), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_stall", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_stall), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_state", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("cache_valid", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__cache_valid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("clk", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("csr_flush_status", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__csr_flush_status), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("flush_flag", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__flush_flag), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("hit", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__hit), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("r_hs", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__r_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("read_data", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__read_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("read_enable", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__read_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("req_block_tag", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__req_block_tag), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,9);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("req_index", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__req_index), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,8,2);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("rst_n", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("set_ptr", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__set_ptr), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,6,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("state", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__state), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("w_hs", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__w_hs), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("write_data", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__instr_cache->varInsert("write_enable", &(TOP.holy_test_harness__DOT__core__DOT__instr_cache__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("aclk", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("araddr", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arburst", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("aresetn", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arlen", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arlock", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arqos", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arsize", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("arvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awaddr", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awburst", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awlen", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awlock", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awqos", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awsize", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("awvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("bid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("bready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("bresp", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("bvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rdata", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rlast", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rresp", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("rvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("wdata", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("wlast", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("wready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("wstrb", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_data->varInsert("wvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_data.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.ADDR_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.DATA_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("ID_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.ID_WIDTH))), true, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("aclk", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.aclk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("araddr", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.araddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arburst", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("aresetn", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.aresetn), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arlen", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arlock", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arqos", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arsize", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("arvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.arvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awaddr", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awaddr), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awburst", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awburst), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awlen", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awlen), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,7,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awlock", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awlock), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awqos", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awqos), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awsize", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awsize), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("awvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.awvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("bid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.bid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("bready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.bready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("bresp", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.bresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("bvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.bvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rdata", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rlast", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rresp", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rresp), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,1,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("rvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.rvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("wdata", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.wdata), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("wlast", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.wlast), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("wready", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.wready), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("wstrb", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.wstrb), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,3,0);
    __Vscopep_holy_test_harness__core__m_axi_instr->varInsert("wvalid", &(TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.wvalid), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("address1", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__address1), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("address2", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__address2), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("address3", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__address3), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,4,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("clk", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__clk), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("read_data1", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__read_data1), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("read_data2", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__read_data2), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("registers", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__registers), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 1, 1 ,0,31 ,31,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("rst_n", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__rst_n), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("write_data", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__write_data), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__regfile->varInsert("write_enable", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__write_enable), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 0);
    __Vscopep_holy_test_harness__core__regfile__unnamedblk1->varInsert("i", &(TOP.holy_test_harness__DOT__core__DOT__regfile__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY|VLVF_SIGNED, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__sign_extender->varInsert("imm_source", &(TOP.holy_test_harness__DOT__core__DOT__sign_extender__DOT__imm_source), false, VLVT_UINT8, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,2,0);
    __Vscopep_holy_test_harness__core__sign_extender->varInsert("immediate", &(TOP.holy_test_harness__DOT__core__DOT__sign_extender__DOT__immediate), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,31,0);
    __Vscopep_holy_test_harness__core__sign_extender->varInsert("raw_src", &(TOP.holy_test_harness__DOT__core__DOT__sign_extender__DOT__raw_src), false, VLVT_UINT32, VLVD_NODIR|VLVF_PUB_RW, 0, 1 ,24,0);
}

Vtop__Syms::~Vtop__Syms() {
    // Tear down scope hierarchy
    __Vhier.remove(0, __Vscopep_holy_test_harness);
    __Vhier.remove(__Vscopep_holy_test_harness, __Vscopep_holy_test_harness__axi);
    __Vhier.remove(__Vscopep_holy_test_harness, __Vscopep_holy_test_harness__core);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__alu_inst);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__arbiter);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__control_unit);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__csr);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__data_cache);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__instr_cache);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__m_axi_data);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__m_axi_instr);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__regfile);
    __Vhier.remove(__Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core__sign_extender);
    __Vhier.remove(__Vscopep_holy_test_harness__core__regfile, __Vscopep_holy_test_harness__core__regfile__unnamedblk1);
    // Clear keys from hierarchy map after values have been removed
    __Vhier.clear();
    if (__Vm_dumping) _traceDumpClose();
    // Tear down scopes
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness, __Vscopep_holy_test_harness = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__axi, __Vscopep_holy_test_harness__axi = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core, __Vscopep_holy_test_harness__core = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__alu_inst, __Vscopep_holy_test_harness__core__alu_inst = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__arbiter, __Vscopep_holy_test_harness__core__arbiter = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__control_unit, __Vscopep_holy_test_harness__core__control_unit = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__csr, __Vscopep_holy_test_harness__core__csr = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__data_cache, __Vscopep_holy_test_harness__core__data_cache = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__instr_cache, __Vscopep_holy_test_harness__core__instr_cache = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__m_axi_data, __Vscopep_holy_test_harness__core__m_axi_data = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__m_axi_instr, __Vscopep_holy_test_harness__core__m_axi_instr = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__regfile, __Vscopep_holy_test_harness__core__regfile = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__regfile__unnamedblk1, __Vscopep_holy_test_harness__core__regfile__unnamedblk1 = nullptr);
    VL_DO_CLEAR(delete __Vscopep_holy_test_harness__core__sign_extender, __Vscopep_holy_test_harness__core__sign_extender = nullptr);
    // Tear down sub module instances
    TOP__holy_test_harness__DOT__core__DOT__m_axi_instr.dtor();
    TOP__holy_test_harness__DOT__core__DOT__m_axi_data.dtor();
    TOP__holy_test_harness__DOT__axi.dtor();
}

void Vtop__Syms::_traceDump() {
    const VerilatedLockGuard lock{__Vm_dumperMutex};
    __Vm_dumperp->dump(VL_TIME_Q());
}

void Vtop__Syms::_traceDumpOpen() {
    const VerilatedLockGuard lock{__Vm_dumperMutex};
    if (VL_UNLIKELY(!__Vm_dumperp)) {
        __Vm_dumperp = new VerilatedVcdC();
        __Vm_modelp->trace(__Vm_dumperp, 0, 0);
        const std::string dumpfile = _vm_contextp__->dumpfileCheck();
        __Vm_dumperp->open(dumpfile.c_str());
        __Vm_dumping = true;
    }
}

void Vtop__Syms::_traceDumpClose() {
    const VerilatedLockGuard lock{__Vm_dumperMutex};
    __Vm_dumping = false;
    VL_DO_CLEAR(delete __Vm_dumperp, __Vm_dumperp = nullptr);
}
